### PR TITLE
fix bug in hashing samples

### PR DESCRIPTION
**Pull request by ericphanson**
The test I added fails on main:
```julia
julia> @test hash(samples) == hash(samples2)
Test Failed at REPL[23]:1
  Expression: hash(samples) == hash(samples2)
   Evaluated: 0x9bab1974999310ac == 0x877a3e1403901e84
```
but passes on this PR.

closes https://github.com/beacon-biosignals/Onda.jl/issues/150

### CODE REVIEW

**Review by palday — APPROVED** [review]
I think this makes sense, but I think @ararslan should weigh in on whether this will mess with anything in Julia internals relying on `Base.hash`

**Review by kimlaberinto — COMMENTED** [review]
Looks good! And seems to make sense as it follows what is recommended in `Base.hash`'s docstring to implement the 2-argument form and calling it recursively to to mix the hashes of the contents with each other.

(docstring from Julia 1.9.4)
```
  hash(x[, h::UInt]) -> UInt

  Compute an integer hash code such that isequal(x,y) implies hash(x)==hash(y). The optional second argument
  h is another hash code to be mixed with the result.

  New types should implement the 2-argument form, typically by calling the 2-argument hash method recursively
  in order to mix hashes of the contents with each other (and with h). Typically, any type that implements
  hash should also implement its own == (hence isequal) to guarantee the property mentioned above. Types
  supporting subtraction (operator -) should also implement widen, which is required to hash values inside
  heterogeneous arrays.
```

**Comment by ericphanson** [comment]
The CI failure looks unrelated but concerning

**Comment by palday** [comment]
I can replicate the CI failure on a local run and it also happens on `main`. Did an update in Arrow break something?

**Comment by palday** [comment]
Tests pass on `main` with Arrow set to 2.6 -- current Arrow release is 2.7.

**Comment by palday** [comment]
see #153.

This is definitely something that needs to be fixed in upstream Arrow, but we have a work around that's trivial

**Review by ararslan — APPROVED** [review]

**Comment by ericphanson** [comment]
> This is definitely something that needs to be fixed in upstream Arrow, but we have a work around that's trivial

Just to say, I don't think there was any bug in the Arrow release, but rather in Onda we were depending on Legolas generating a specific `fromarrow` method that we stopped generating after https://github.com/beacon-biosignals/Legolas.jl/pull/106, since `Samples` has some custom serialization as it is not a Legolas `@version`. Resolved by #153 in any case.

**Pull request merged**
